const cst = {
    ADD_CONTACT: "ADD_CONTACT",
    ADD_CONTACT_SUCCESS: "ADD_CONTACT_SUCCESS",
    
    ADD_GROUP: "ADD_GROUP",
    ADD_GROUP_SUCCESS: "ADD_GROUP_SUCCESS",
    
    ADD_ADDR: "ADD_ADDR",
    ADD_ADDR_SUCCESS: "ADD_ADDR_SUCCESS",
    
    ADD_PHONE: "ADD_PHONE",
    ADD_PHONE_SUCCESS: "ADD_PHONE_SUCCESS",
    
    ADD_EMAIL: "ADD_EMAIL",
    ADD_EMAIL_SUCCESS: "ADD_EMAIL_SUCCESS",
    
    ADD_PORTRAIT: "ADD_PORTRAIT",
    ADD_PORTRAIT_SUCCESS: "ADD_PORTRAIT_SUCCESS",
    
    ADD_THUMBNAIL: "ADD_THUMBNAIL",
    ADD_THUMBNAIL_SUCCESS: "ADD_THUMBNAIL_SUCCESS",
    
    ADD_TWITTER: "ADD_TWITTER",
    ADD_TWITTER_SUCCESS: "ADD_TWITTER_SUCCESS",
    
    ADD_CONTACT_GROUP: "ADD_CONTACT_GROUP",
    ADD_CONTACT_GROUP_SUCCESS: "ADD_CONTACT_GROUP_SUCCESS",
    
    LIST_CONTACTS: "LIST_CONTACTS",
    LIST_CONTACTS_SUCCESS: "LIST_CONTACTS_SUCCESS",
    
    LIST_ADDRESSES: "LIST_ADDRESSES",
    LIST_ADDRESSES_SUCCESS: "LIST_ADDRESSES_SUCCESS",
    
    LIST_PHONES: "LIST_PHONES",
    LIST_PHONES_SUCCESS: "LIST_PHONES_SUCCESS",
    
    LIST_EMAILS: "LIST_EMAILS",
    LIST_EMAILS_SUCCESS: "LIST_EMAILS_SUCCESS",
    
    LIST_GROUPS: "LIST_GROUPS",
    LIST_GROUPS_SUCCESS: "LIST_GROUPS_SUCCESS",
    
    LIST_TWITTER: "LIST_TWITTER",
    LIST_TWITTER_SUCCESS: "LIST_TWITTER_SUCCESS",
    
    LIST_THUMBNAILS: "LIST_THUMBNAILS",
    LIST_THUMBNAILS_SUCCESS: "LIST_THUMBNAILS_SUCCESS",
    
    LIST_PORTRAITS: "LIST_PORTRAITS",
    LIST_PORTRAITS_SUCCESS: "LIST_PORTRAITS_SUCCESS",
}

export default cst