const cst = {
    ADD_CONTACT: "ADD_CONTACT",
    ADD_CONTACT_SUCCESS: "ADD_CONTACT_SUCCESS",

    ADD_GROUP: "ADD_GROUP",
    ADD_GROUP_SUCCESS: "ADD_GROUP_SUCCESS",

    ADD_ADDR: "ADD_ADDR",
    ADD_ADDR_SUCCESS: "ADD_ADDR_SUCCESS",

    ADD_PHONE: "ADD_PHONE",
    ADD_PHONE_SUCCESS: "ADD_PHONE_SUCCESS",

    ADD_EMAIL: "ADD_EMAIL",
    ADD_EMAIL_SUCCESS: "ADD_EMAIL_SUCCESS",

    ADD_PORTRAIT: "ADD_PORTRAIT",
    ADD_PORTRAIT_SUCCESS: "ADD_PORTRAIT_SUCCESS",

    ADD_THUMBNAIL: "ADD_THUMBNAIL",
    ADD_THUMBNAIL_SUCCESS: "ADD_THUMBNAIL_SUCCESS",

    ADD_TWITTER: "ADD_TWITTER",
    ADD_TWITTER_SUCCESS: "ADD_TWITTER_SUCCESS",

    ADD_CONTACT_GROUP: "ADD_CONTACT_GROUP",
    ADD_CONTACT_GROUP_SUCCESS: "ADD_CONTACT_GROUP_SUCCESS",

    DELETE_CONTACT: "DELETE_CONTACT",
    DELETE_CONTACT_SUCCESS: "DELETE_CONTACT_SUCCESS",

    DELETE_GROUP: "DELETE_GROUP",
    DELETE_GROUP_SUCCESS: "DELETE_GROUP_SUCCESS",

    DELETE_ADDR: "DELETE_ADDR",
    DELETE_ADDR_SUCCESS: "DELETE_ADDR_SUCCESS",

    DELETE_PHONE: "DELETE_PHONE",
    DELETE_PHONE_SUCCESS: "DELETE_PHONE_SUCCESS",

    DELETE_EMAIL: "DELETE_EMAIL",
    DELETE_EMAIL_SUCCESS: "DELETE_EMAIL_SUCCESS",

    DELETE_PORTRAIT: "DELETE_PORTRAIT",
    DELETE_PORTRAIT_SUCCESS: "DELETE_PORTRAIT_SUCCESS",

    DELETE_THUMBNAIL: "DELETE_THUMBNAIL",
    DELETE_THUMBNAIL_SUCCESS: "DELETE_THUMBNAIL_SUCCESS",

    DELETE_TWITTER: "DELETE_TWITTER",
    DELETE_TWITTER_SUCCESS: "DELETE_TWITTER_SUCCESS",

    DELETE_CONTACT_GROUP: "DELETE_CONTACT_GROUP",
    DELETE_CONTACT_GROUP_SUCCESS: "DELETE_CONTACT_GROUP_SUCCESS",

    LIST_CONTACTS: "LIST_CONTACTS",
    LIST_CONTACTS_SUCCESS: "LIST_CONTACTS_SUCCESS",

    LIST_ADDRESSES: "LIST_ADDRESSES",
    LIST_ADDRESSES_SUCCESS: "LIST_ADDRESSES_SUCCESS",

    LIST_PHONES: "LIST_PHONES",
    LIST_PHONES_SUCCESS: "LIST_PHONES_SUCCESS",

    LIST_EMAILS: "LIST_EMAILS",
    LIST_EMAILS_SUCCESS: "LIST_EMAILS_SUCCESS",

    LIST_GROUPS: "LIST_GROUPS",
    LIST_GROUPS_SUCCESS: "LIST_GROUPS_SUCCESS",

    LIST_TWITTER: "LIST_TWITTER",
    LIST_TWITTER_SUCCESS: "LIST_TWITTER_SUCCESS",

    LIST_THUMBNAILS: "LIST_THUMBNAILS",
    LIST_THUMBNAILS_SUCCESS: "LIST_THUMBNAILS_SUCCESS",

    LIST_PORTRAITS: "LIST_PORTRAITS",
    LIST_PORTRAITS_SUCCESS: "LIST_PORTRAITS_SUCCESS",

    LIST_PHONE_BY_CONTACT_ID: "LIST_PHONE_BY_CONTACT_ID",
    LIST_PHONE_BY_CONTACT_ID_SUCCESS: "LIST_PHONE_BY_CONTACT_ID_SUCCESS",

    LIST_ADDR_BY_CONTACT_ID: "LIST_ADDR_BY_CONTACT_ID",
    LIST_ADDR_BY_CONTACT_ID_SUCCESS: "LIST_ADDR_BY_CONTACT_ID_SUCCESS",

    LIST_GROUP_BY_CONTACT_ID: "LIST_GROUP_BY_CONTACT_ID",
    LIST_GROUP_BY_CONTACT_ID_SUCCESS: "LIST_GROUP_BY_CONTACT_ID_SUCCESS",

    LIST_EMAIL_BY_CONTACT_ID: "LIST_EMAIL_BY_CONTACT_ID",
    LIST_EMAIL_BY_CONTACT_ID_SUCCESS: "LIST_EMAIL_BY_CONTACT_ID_SUCCESS",

    LIST_TWITTER_BY_CONTACT_ID: "LIST_TWITTER_BY_CONTACT_ID",
    LIST_TWITTER_BY_CONTACT_ID_SUCCESS: "LIST_TWITTER_BY_CONTACT_ID_SUCCESS",

    LIST_THUMBNAIL_BY_CONTACT_ID: "LIST_THUMBNAIL_BY_CONTACT_ID",
    LIST_THUMBNAIL_BY_CONTACT_ID_SUCCESS: "LIST_THUMBNAIL_BY_CONTACT_ID_SUCCESS",

    LIST_PORTRAIT_BY_CONTACT_ID: "LIST_PORTRAIT_BY_CONTACT_ID",
    LIST_PORTRAIT_BY_CONTACT_ID_SUCCESS: "LIST_PORTRAIT_BY_CONTACT_ID_SUCCESS",

    UPDATE_CONTACT: "UPDATE_CONTACT",
    UPDATE_CONTACT_SUCCESS: "UPDATE_CONTACT_SUCCESS",

    UPDATE_GROUP: "UPDATE_GROUP",
    UPDATE_GROUP_SUCCESS: "UPDATE_GROUP_SUCCESS",

    UPDATE_ADDR: "UPDATE_ADDR",
    UPDATE_ADDR_SUCCESS: "UPDATE_ADDR_SUCCESS",

    UPDATE_PHONE: "UPDATE_PHONE",
    UPDATE_PHONE_SUCCESS: "UPDATE_PHONE_SUCCESS",

    UPDATE_EMAIL: "UPDATE_EMAIL",
    UPDATE_EMAIL_SUCCESS: "UPDATE_EMAIL_SUCCESS",

    UPDATE_PORTRAIT: "UPDATE_PORTRAIT",
    UPDATE_PORTRAIT_SUCCESS: "UPDATE_PORTRAIT_SUCCESS",

    UPDATE_THUMBNAIL: "UPDATE_THUMBNAIL",
    UPDATE_THUMBNAIL_SUCCESS: "UPDATE_THUMBNAIL_SUCCESS",

    UPDATE_TWITTER: "UPDATE_TWITTER",
    UPDATE_TWITTER_SUCCESS: "UPDATE_TWITTER_SUCCESS",

    UPDATE_CONTACT_GROUP: "UPDATE_CONTACT_GROUP",
    UPDATE_CONTACT_GROUP_SUCCESS: "UPDATE_CONTACT_GROUP_SUCCESS",

    SELECT_A_CONTACT: "SELECT_A_CONTACT",
    SELECT_A_CONTACT_SUCCESS: "SELECT_A_CONTACT_SUCCESS",
    SELECT_CONTACT_NULL: "SELECT_CONTACT_NULL",

    MENU_ADD: "MENU_ADD",
    MENU_DISPLAY: "MENU_DISPLAY",
    MENU_NEUTRAL: "MENU_NEUTRAL",
}

export default cst